# starship config.toml

# Use custom format
format = """
$directory\
$status\
$character """

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
truncation_length=1
read_only = " ğŸ”’"
read_only_style = "red bold"
style = "blue bold"
format = "[$path ]($style)[$read_only]($read_only_style)"

[character]
success_symbol = "[â¯](bold green)"
error_symbol= "[âœ–](bold red)"
vicmd_symbol="[â®](bold yellow)"

